### ISSUE TITLE
HorizonLauncher looks bad on hidpi devices (eg retina)

### ISSUE THREAD

**Issue by globau** [HorizonLauncher/Client#82] opened 2016-03-23 23:51 UTC
on a hidpi screen, such as a retina screen on apple hardware, the launcher is low dpi.

this results in a very pixelated display making it very unappealing.

**Comment by TheDarocker** [comment] 2016-03-24 00:01
HI! Can you post a screenshot of what the launcher looks like?

**Comment by globau** [comment] 2016-03-24 03:35
make sure you view the screenshot at 100% zoom; compare the text from your wizard with the same text in the browser.  note this hidpi issues applies to all content in the launcher.  i don't have the ability to test on windows, but you can easily emulate hidpi by altering the pixel ratio.

<img width="1680" alt="screenshot 2016-03-24 11 24 18 2" src="https://cloud.githubusercontent.com/assets/872825/14007595/3361ddd8-f1b3-11e5-9af6-cb49e72b09f6.png">

**Comment by TheDarocker** [comment] 2016-03-25 18:07
Are you talking about the fonts/icons or the launcher itself? I can't really tell what the issue is

**Comment by TheDarocker** [comment] 2016-03-25 18:10
Oh I see what you mean- that's odd.

**Comment by thomassross** [comment] 2016-04-26 20:10
Hi,

Sorry for the late reply! This issue seems to be fixed in Qt 5.6+, however, [we're stuck on Qt 5.5 for now](https://github.com/HorizonLauncher/Client/issues/81#issuecomment-201550759). As soon as major distributions package QWebEngine, we will switch to that, fixing this issue.

We will be including SVG icons with #88, which will hopefully increase the quality of the icons on high resolution displays.

Thanks.

**Closed as completed by thomassross** 2016-04-26 20:10 UTC
Labels: bug
